services:

  redis:
    restart: on-failure
    container_name: redis-ocr
    build:
      context: docker/redis
    security_opt:
      - no-new-privileges:true
    ports:
      - 6389:6389
    command: redis-server --loglevel warning
    # Run as privileged to allow the container to change the vm.overcommit_memory setting
    privileged: true
    volumes:
      - ./data/redis:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  nginx:
    restart: on-failure
    container_name: nginx-ocr
    build:
      context: docker/nginx
    volumes:
      - ./certs:/etc/nginx/certs
    ports:
      - "8082:443"

  postgres:
    restart: on-failure
    container_name: postgresql-ocr
    build:
      context: docker/postgres
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file: ./.env
    ports:
      - "5435:5435"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  custom:
    driver: bridge
