version: "3.8"


volumes:
  pgdata:

services:

  redis:
    restart: on-failure
    build:
      context: docker/redis/
    security_opt:
      - no-new-privileges:true
    ports:
      - 6379:6379
    command: redis-server --loglevel warning
    # Run as privileged to allow the container to change the vm.overcommit_memory setting
    privileged: true
    volumes:
      - ./data/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  nginx:
    restart: on-failure
    build:
      context: docker/nginx/
    ports:
      - "8080:80"

  postgres:
    restart: on-failure
    build:
      context: docker/postgres/
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
