[tool.poetry]
name = "ocr-playground"
version = "0.1.0"
description = ""
authors = ["victory-sokolov <viktorsokolov.and@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
fastapi = "^0.65.2"
uvicorn = "^0.12.1"
opencv-python = "4.2.0.32"
jinja2 = "^2.11.2"
python-multipart = "^0.0.5"
numpy = "^1.19.2"
imutils = "^0.5.3"
python-dotenv = "^0.14.0"
rq = "^1.5.2"
redis = "^3.5.3"
aiofiles = "^0.5.0"
easyocr = "1.4.1"
spacy = "^3.2.0"
paddleocr = "^2.3.0"
paddlepaddle = "^2.2.0"
dependency-injector = "^4.37.0"
numba = "^0.54.1"
Pillow = "8.2.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
isort = "^5.10.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
