[tool.poetry]
name = "ocr-playground"
version = "0.1.0"
description = ""
authors = ["victory-sokolov <viktorsokolov.and@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
fastapi = "^0.61.1"
uvicorn = "^0.12.1"
opencv-python = "^4.4.0"
jinja2 = "^2.11.2"
python-multipart = "^0.0.5"
numpy = "^1.19.2"
imutils = "^0.5.3"
pytesseract = "^0.3.6"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
