name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          ignore: DL3008

      - name: Run Super-Linter
        uses: github/super-linter@v4.8.7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
